In [ ]:
import pandas as pd
import numpy
from sklearn.feature_selection import *

# Data Processing

In [ ]:
data = pd.read_csv("DataTulum.csv", header=None)

In [ ]:
hour = []
minute = []
time = []
day = data[1].to_numpy()
location = data[3].to_numpy()
prevAct = data[4].to_numpy()
for i in data[2]:
  t = i
  ind = t.find(":")
  h = int(t[:ind])
  m = int(t[ind+1:ind+3])
  hour.append(h)
  minute.append(m)
  time.append(h*60+m)
hour = numpy.array(hour)
minute = numpy.array(minute)
time = numpy.array(time)

In [ ]:
print(hour.shape,minute.shape,time.shape,day.shape,location.shape,prevAct.shape)

(25275,) (25275,) (25275,) (25275,) (25275,) (25275,)


In [ ]:
l = len(day)
day = day[1:].reshape((l-1,1))
hour = hour[1:].reshape((l-1,1))
minute = minute[1:].reshape((l-1,1))
time = time[1:].reshape((l-1,1))
location = location[1:].reshape((l-1,1))
prevAct = prevAct[:-1].reshape((l-1,1))

In [ ]:
print(hour.shape,minute.shape,time.shape,day.shape,location.shape,prevAct.shape)

(25274, 1) (25274, 1) (25274, 1) (25274, 1) (25274, 1) (25274, 1)


In [ ]:
arrays = [day,location,prevAct]
arr = []
for ar in arrays:
  dic = {}
  ind = 0
  temp = []
  for ii in ar:
    i = ii.item(0)
    if i not in dic:
      dic[i] = ind
      ind += 1
    temp.append(dic[i])
  arr.append(temp)
day = numpy.array(arr[0]).reshape((l-1,1))
location = numpy.array(arr[1]).reshape((l-1,1))
prevAct = numpy.array(arr[2]).reshape((l-1,1))

In [ ]:
X = numpy.concatenate((day,hour,minute,time,location,prevAct),axis = 1)
Y = data[4].to_numpy()
Y = Y[1:]

In [ ]:
print(X.shape,Y.shape)

(25274, 6) (25274,)


# Tests

In [ ]:
# Aruba
# (day,hour,minute,time,location,prevAct)
print(chi2(X,Y))
print(f_classif(X,Y))

(array([4.16423308e+01, 6.14142349e+03, 3.95769847e+02, 3.54914516e+05,
       9.48729070e+03, 2.25035906e+04]), array([4.66526000e-03, 0.00000000e+00, 6.95833596e-71, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00]))
(array([   1.50837343,  159.4739641 ,    1.88818603,  159.21038017,
       1158.33859439, 1205.46170339]), array([0.06334855, 0.        , 0.008268  , 0.        , 0.        ,
       0.        ]))


In [ ]:
# Milan
# (day,hour,minute,time,location,prevAct)
print(chi2(X,Y))
print(f_classif(X,Y))

(array([   46.6711462 ,   193.25735989,   230.14265687, 11386.40353041,
        1716.65142734,   984.50506241]), array([5.35963507e-003, 6.04717331e-028, 4.31844246e-035, 0.00000000e+000,
       0.00000000e+000, 1.12622361e-191]))
(array([ 1.32112074,  4.3980824 ,  0.98499496,  4.47526489, 21.54412875,
       28.69440225]), array([1.38442354e-01, 3.33741875e-11, 4.85761734e-01, 1.77719751e-11,
       8.55659027e-64, 2.10593628e-80]))


In [ ]:
# Tulum
# (day,hour,minute,time,location,prevAct)
print(chi2(X,Y))
print(f_classif(X,Y))

(array([   425.18686467,   7170.25616938,    469.98908198, 414065.22190534,
        89377.76242057,  54231.07209077]), array([1.16521777e-69, 0.00000000e+00, 1.02068451e-78, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00]))
(array([ 10.7443796 , 126.89690173,   1.39653535, 124.86308018,
       723.45668641, 622.02875947]), array([4.28727262e-55, 0.00000000e+00, 6.48839000e-02, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00]))
